Lab1
IgorChaikin/Android-projects pull request #3
Opened 2020-12-02 13:05 UTC by IgorChaikin

2020-12-02 17:54 UTC, gmltA requested changes

2020-12-02 17:54 UTC, gmltA commented on lab1/ValuesConverter/app/build.gradle
> +        versionName "1.0"
Signing and versioning are not implemented. See requirements.

2020-12-05 16:58 UTC, IgorChaikin commented on lab1/ValuesConverter/app/build.gradle
> +        versionName "1.0"
Requested changes have been made in file 'lab1/ValuesConverter/app/build.gradle' (commit 'change graddle').

2020-12-07 14:43 UTC, gmltA requested changes
APK signing is still not implemented.

2020-12-08 19:12 UTC, IgorChaikin commented on lab1/ValuesConverter/app/build.gradle
> +        versionName "1.0"
Add signing configs in lab1/ValuesConverter/app/build.gradle

2020-12-08 19:22 UTC, IgorChaikin commented on lab1/ValuesConverter/app/build.gradle
> +        versionName "1.0"
Add signing configs in lab1/ValuesConverter/app/build.gradle

2020-12-09 16:21 UTC, gmltA approved these changes

2020-12-09 17:11 UTC, merged