Lab3
IgorChaikin/Android-projects pull request #5
Opened 2020-12-18 14:14 UTC by IgorChaikin

2020-12-20 15:45 UTC, gmltA requested changes
Выдаліце, калі ласка, другую лабу з гэтага ПРа.

2020-12-20 17:24 UTC, IgorChaikin commented
Удалил

2020-12-27 15:21 UTC, gmltA commented on lab3/FireBaseGame/app/src/main/java/com/laba/firebasegame/Board.kt
> +const val SHIPS_COUNT = 1
One ship?

2020-12-27 19:29 UTC, IgorChaikin commented on lab3/FireBaseGame/app/src/main/java/com/laba/firebasegame/Board.kt
> +const val SHIPS_COUNT = 1
Один корабль был на этапе отладки для облегчения тестирования. Похоже, забыл об этом. Сейчас исправил количество.

2020-12-28 15:42 UTC, gmltA commented
Can you record a video? I can't get past the auth action.

2020-12-29 11:11 UTC, IgorChaikin commented
https://user-images.githubusercontent.com/60624900/103279802-bb123780-49df-11eb-9959-cb5e406e0480.mp4

2020-12-29 21:10 UTC, IgorChaikin commented
https://user-images.githubusercontent.com/60624900/103314179-4b2d9c80-4a33-11eb-8cdb-ad2eee030eb4.mp4

2020-12-30 13:36 UTC, gmltA commented
>  login.mp4

And the game process, please)

2020-12-31 15:10 UTC, IgorChaikin commented
https://user-images.githubusercontent.com/60624900/103415466-3ec05580-4b93-11eb-8e2f-c8f7486e86e5.mp4

2021-01-03 15:22 UTC, gmltA approved these changes
Okay. Goog luck.

2021-01-04 12:09 UTC, merged